hunav_loader:
  ros__parameters:
    yaml_base_name: agents_cafe
    simulator: Gazebo Classic
    map: cafe
    publish_people: true
    global_goals:
      1:
        x: -3.7
        y: -3.29
      2:
        x: 0.184
        y: -4.85
      3:
        x: 0.269
        y: -3.204
      4:
        x: 2.963
        y: 0.113
      5:
        x: -2.88
        y: 0.028
      6:
        x: 2.0
        y: 4.226
      7:
        x: 0.411
        y: -6.039
      8:
        x: -1.5
        y: 2.5
      9:
        x: 1.5
        y: 1.5
      10:
        x: -0.5
        y: -2.0
    agents:
    - agent1
    - agent2
    - agent3
    - agent4
    - agent5
    - agent6
    - agent7
    - agent8
    - agent9
    - agent10
    - agent11
    - agent12
    - agent13
    - agent14
    - agent15
    - agent16
    - agent17
    - agent18
    - agent19
    - agent20
    - agent21
    - agent22
    - agent23
    - agent24
    - agent25
    agent1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 1.0794
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 1.824
        y: -8.931
        z: 1.25
        h: 0.951
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.2
        obstacle_force_factor: 9.89
        social_force_factor: 18.04
        other_force_factor: 20.0
      goals:
      - 9
      - 4
    agent2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 1.0884
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -2.165
        y: -3.027
        z: 1.25
        h: -2.04
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.83
        obstacle_force_factor: 18.04
        social_force_factor: 21.97
        other_force_factor: 20.0
      goals:
      - 3
      - 10
    agent3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 1.0162
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -0.432
        y: 4.798
        z: 1.25
        h: 0.694
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.12
        obstacle_force_factor: 16.3
        social_force_factor: 22.42
        other_force_factor: 20.0
      goals:
      - 3
      - 9
    agent4:
      id: 4
      group_id: -1
      skin: 0
      max_vel: 0.9637
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 1.269
        y: -2.217
        z: 1.25
        h: -1.041
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 4.28
        obstacle_force_factor: 14.71
        social_force_factor: 20.24
        other_force_factor: 20.0
      goals:
      - 9
      - 3
    agent5:
      id: 5
      group_id: -1
      skin: 1
      max_vel: 0.956
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.803
        y: -6.354
        z: 1.25
        h: 1.881
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.35
        obstacle_force_factor: 13.31
        social_force_factor: 23.62
        other_force_factor: 20.0
      goals:
      - 8
      - 1
    agent6:
      id: 6
      group_id: -1
      skin: 2
      max_vel: 1.0826
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -0.764
        y: -2.716
        z: 1.25
        h: 1.628
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.35
        obstacle_force_factor: 18.86
        social_force_factor: 23.89
        other_force_factor: 20.0
      goals:
      - 10
      - 4
    agent7:
      id: 7
      group_id: -1
      skin: 0
      max_vel: 1.1728
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 2.776
        y: -3.564
        z: 1.25
        h: 2.96
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.22
        obstacle_force_factor: 14.36
        social_force_factor: 20.27
        other_force_factor: 20.0
      goals:
      - 1
      - 8
    agent8:
      id: 8
      group_id: -1
      skin: 1
      max_vel: 1.2522
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -0.065
        y: 0.484
        z: 1.25
        h: -0.119
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.45
        obstacle_force_factor: 8.96
        social_force_factor: 22.59
        other_force_factor: 20.0
      goals:
      - 8
      - 7
    agent9:
      id: 9
      group_id: -1
      skin: 2
      max_vel: 1.2048
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -4.889
        y: 0.953
        z: 1.25
        h: -1.678
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.13
        obstacle_force_factor: 17.67
        social_force_factor: 17.03
        other_force_factor: 20.0
      goals:
      - 10
      - 4
    agent10:
      id: 10
      group_id: -1
      skin: 0
      max_vel: 1.1461
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.487
        y: 5.416
        z: 1.25
        h: 0.507
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.99
        obstacle_force_factor: 13.33
        social_force_factor: 19.66
        other_force_factor: 20.0
      goals:
      - 3
      - 6
    agent11:
      id: 11
      group_id: -1
      skin: 1
      max_vel: 1.0049
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.736
        y: -2.781
        z: 1.25
        h: -1.674
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.5
        obstacle_force_factor: 11.85
        social_force_factor: 18.39
        other_force_factor: 20.0
      goals:
      - 4
      - 2
    agent12:
      id: 12
      group_id: -1
      skin: 2
      max_vel: 0.9527
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -0.199
        y: -8.014
        z: 1.25
        h: 2.414
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.14
        obstacle_force_factor: 15.15
        social_force_factor: 21.6
        other_force_factor: 20.0
      goals:
      - 9
      - 5
    agent13:
      id: 13
      group_id: -1
      skin: 0
      max_vel: 1.1427
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -1.594
        y: -0.605
        z: 1.25
        h: 2.873
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.79
        obstacle_force_factor: 14.69
        social_force_factor: 18.99
        other_force_factor: 20.0
      goals:
      - 4
      - 2
    agent14:
      id: 14
      group_id: -1
      skin: 1
      max_vel: 1.2631
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 2.325
        y: 5.192
        z: 1.25
        h: 1.984
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.58
        obstacle_force_factor: 16.41
        social_force_factor: 18.86
        other_force_factor: 20.0
      goals:
      - 3
      - 9
    agent15:
      id: 15
      group_id: -1
      skin: 2
      max_vel: 0.9581
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -1.827
        y: -4.939
        z: 1.25
        h: 0.975
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.14
        obstacle_force_factor: 16.0
        social_force_factor: 19.22
        other_force_factor: 20.0
      goals:
      - 7
      - 10
    agent16:
      id: 16
      group_id: -1
      skin: 0
      max_vel: 0.9724
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.036
        y: 1.078
        z: 1.25
        h: -0.122
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.99
        obstacle_force_factor: 18.57
        social_force_factor: 20.45
        other_force_factor: 20.0
      goals:
      - 6
      - 7
    agent17:
      id: 17
      group_id: -1
      skin: 1
      max_vel: 1.2152
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -4.832
        y: -7.438
        z: 1.25
        h: -2.134
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.68
        obstacle_force_factor: 13.58
        social_force_factor: 20.13
        other_force_factor: 20.0
      goals:
      - 8
      - 10
    agent18:
      id: 18
      group_id: -1
      skin: 2
      max_vel: 1.0438
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 1.799
        y: -6.322
        z: 1.25
        h: 2.568
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.73
        obstacle_force_factor: 16.92
        social_force_factor: 21.11
        other_force_factor: 20.0
      goals:
      - 1
      - 8
    agent19:
      id: 19
      group_id: -1
      skin: 0
      max_vel: 1.1727
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 0.548
        y: -5.427
        z: 1.25
        h: -1.509
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.01
        obstacle_force_factor: 15.27
        social_force_factor: 17.02
        other_force_factor: 20.0
      goals:
      - 7
      - 4
    agent20:
      id: 20
      group_id: -1
      skin: 1
      max_vel: 0.8722
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 1.139
        y: 3.835
        z: 1.25
        h: -2.05
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.39
        obstacle_force_factor: 17.03
        social_force_factor: 19.2
        other_force_factor: 20.0
      goals:
      - 7
      - 5
    agent21:
      id: 21
      group_id: -1
      skin: 2
      max_vel: 0.9457
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.233
        y: -8.602
        z: 1.25
        h: 0.593
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 4.01
        obstacle_force_factor: 12.78
        social_force_factor: 19.92
        other_force_factor: 20.0
      goals:
      - 9
      - 4
    agent22:
      id: 22
      group_id: -1
      skin: 0
      max_vel: 1.0331
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 2.604
        y: 2.998
        z: 1.25
        h: 2.048
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 3.04
        obstacle_force_factor: 18.5
        social_force_factor: 17.55
        other_force_factor: 20.0
      goals:
      - 9
      - 1
    agent23:
      id: 23
      group_id: -1
      skin: 1
      max_vel: 1.1146
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.815
        y: 3.524
        z: 1.25
        h: -1.182
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.83
        obstacle_force_factor: 19.65
        social_force_factor: 20.49
        other_force_factor: 20.0
      goals:
      - 8
      - 9
    agent24:
      id: 24
      group_id: -1
      skin: 2
      max_vel: 1.1254
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 3.367
        y: -1.115
        z: 1.25
        h: -2.141
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 4.26
        obstacle_force_factor: 10.03
        social_force_factor: 23.44
        other_force_factor: 20.0
      goals:
      - 7
      - 10
    agent25:
      id: 25
      group_id: -1
      skin: 0
      max_vel: 0.9525
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.541
        y: -4.915
        z: 1.25
        h: -3.134
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.92
        obstacle_force_factor: 10.98
        social_force_factor: 21.87
        other_force_factor: 20.0
      goals:
      - 5
      - 3
